name: "App build"

on:
  release:
    types: [prereleased]

jobs:
  IOS_BUILD:
    name: "iOS Build & Deploy"
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Decrypt ios keys
        run: sh ./.github/scripts/decrypt_ios_keys.sh
        env:
          APPSTORE_API_KEY: ${{ secrets.APPSTORE_API_KEY }}
          APPSTORE_API_KEY_PASSPHRASE: ${{ secrets.APPSTORE_API_KEY_PASSPHRASE }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'
          bundler-cache: true

      - name: Node modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle check || bundle install

      - name: Build & Deploy
        run: bundle exec fastlane ios build
        env:
          FASTLANE_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}

  ANDROID_BUILD:
    name: "Android Build & Deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_keys.sh
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_PASSPHRASE: ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}
#          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
#          SERVICE_ACCOUNT_PASSPHRASE: ${{ secrets.SERVICE_ACCOUNT_PASSPHRASE }}

      - name: Node modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'
          bundler-cache: true

      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn

      - name: Install Fastlane
        run: gem install fastlane

      - name: Build & Deploy
        run: fastlane android build
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{secrets.RELEASE_KEYSTORE_PASSWORD}}
          RELEASE_KEYSTORE_KEY_PASSWORD: ${{secrets.RELEASE_KEYSTORE_PASSWORD}}
          RELEASE_KEYSTORE_ALIAS: ${{secrets.RELEASE_KEYSTORE_ALIAS}}
