name: "App build"

on:
  release:
    types: [prereleased]

jobs:
  IOS_BUILD:
    name: "iOS Build & Deploy"
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Decrypt ios keys
        run: sh ./.github/scripts/decrypt_ios_keys.sh
        env:
          APPSTORE_API_KEY: ${{ secrets.APPSTORE_API_KEY }}
          SECRETS_PASSPHRASE: ${{ secrets.SECRETS_PASSPHRASE }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'
          bundler-cache: true

      - name: Node modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle check || bundle install

      - name: Restore Pods cache
        uses: actions/cache@v2
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods
        run: cd ios && pod install --repo-update && cd ..

      - name: Build & Deploy
        run: bundle exec fastlane ios pre_release
        env:
          FASTLANE_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}

  ANDROID_BUILD:
    name: "Android Build & Deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_keys.sh
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_INFO: ${{ secrets.RELEASE_KEYSTORE_INFO }}
          SECRETS_PASSPHRASE: ${{ secrets.SECRETS_PASSPHRASE }}
#          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: release.keystore.asc
          path: release.keystore.asc

      - name: Node modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'
          bundler-cache: true

      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn

      - name: Install Fastlane
        run: gem install fastlane

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle check || bundle install

      - name: Build & Deploy
        run: bundle exec fastlane android pre_release
